type: kubernetes.io/tls
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2021-09-28T16:14:00Z"
  name: tower-secret-tls
#  namespace: awx
data:
  tls.crt: LS0t...JQ0FURS0tLS0t
  tls.key: LS0t...FWS0tLS0tCgo=
