---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  hostname: awx-laptop.demo.local
  image: quay.io/ansible/awx
  image_version: latest
  image_pull_policy: Always
  admin_user: admin
  admin_password_secret: awx-admin-password
  ingress_type: Ingress
  ingress_tls_secret: awx-secret-tls
  postgres_storage_requirements:
    requests:
      storage: 8Gi