---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-admin-password
    literals:
      - password="admin@F5demo.com"

  - name: awx-postgres-configuration
    literals:
      - host=awx-postgres-15
      - port=5432
      - database=awx
      - username=awx
      - password="adminPSQL@F5demo.com"
      - type=managed

resources:
  - awx.yml

# Specify a custom namespace in which to install AWX
namespace: awx
